/*
 * generated by Xtext 2.9.2
 */
package nl.coenbijlsma.languages.d3ql.parser.antlr;

import com.google.inject.Inject;
import nl.coenbijlsma.languages.d3ql.parser.antlr.internal.InternalD3qlParser;
import nl.coenbijlsma.languages.d3ql.services.D3qlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class D3qlParser extends AbstractAntlrParser {

	@Inject
	private D3qlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalD3qlParser createParser(XtextTokenStream stream) {
		return new InternalD3qlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Query";
	}

	public D3qlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(D3qlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
