/*
 * generated by Xtext 2.9.2
 */
package nl.coenbijlsma.languages.d3ql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class D3qlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/coenbijlsma/languages/d3ql/parser/antlr/internal/InternalD3ql.tokens");
	}
}
