/**
 * generated by Xtext 2.9.2
 */
package nl.coenbijlsma.languages.d3ql.d3ql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aggregate Root</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.coenbijlsma.languages.d3ql.d3ql.AggregateRoot#getAlias <em>Alias</em>}</li>
 * </ul>
 *
 * @see nl.coenbijlsma.languages.d3ql.d3ql.D3qlPackage#getAggregateRoot()
 * @model
 * @generated
 */
public interface AggregateRoot extends Named
{
  /**
   * Returns the value of the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alias</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' containment reference.
   * @see #setAlias(Alias)
   * @see nl.coenbijlsma.languages.d3ql.d3ql.D3qlPackage#getAggregateRoot_Alias()
   * @model containment="true"
   * @generated
   */
  Alias getAlias();

  /**
   * Sets the value of the '{@link nl.coenbijlsma.languages.d3ql.d3ql.AggregateRoot#getAlias <em>Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' containment reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(Alias value);

} // AggregateRoot
