/**
 * generated by Xtext 2.9.2
 */
package nl.coenbijlsma.languages.d3ql.d3ql;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see nl.coenbijlsma.languages.d3ql.d3ql.D3qlFactory
 * @model kind="package"
 * @generated
 */
public interface D3qlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "d3ql";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.coenbijlsma.nl/languages/d3ql/D3ql";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "d3ql";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  D3qlPackage eINSTANCE = nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl.init();

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.QueryImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 0;

  /**
   * The feature id for the '<em><b>From Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__FROM_STATEMENT = 0;

  /**
   * The feature id for the '<em><b>Select Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__SELECT_STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.FromStatementImpl <em>From Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.FromStatementImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getFromStatement()
   * @generated
   */
  int FROM_STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Aggregates</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_STATEMENT__AGGREGATES = 0;

  /**
   * The number of structural features of the '<em>From Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.NamedImpl <em>Named</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.NamedImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getNamed()
   * @generated
   */
  int NAMED = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED__NAME = 0;

  /**
   * The number of structural features of the '<em>Named</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.AggregateRootImpl <em>Aggregate Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.AggregateRootImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getAggregateRoot()
   * @generated
   */
  int AGGREGATE_ROOT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATE_ROOT__NAME = NAMED__NAME;

  /**
   * The feature id for the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATE_ROOT__ALIAS = NAMED_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Aggregate Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATE_ROOT_FEATURE_COUNT = NAMED_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.AliasImpl <em>Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.AliasImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getAlias()
   * @generated
   */
  int ALIAS = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS__NAME = NAMED__NAME;

  /**
   * The number of structural features of the '<em>Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_FEATURE_COUNT = NAMED_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectStatementImpl <em>Select Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectStatementImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getSelectStatement()
   * @generated
   */
  int SELECT_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_STATEMENT__EXPRESSIONS = 0;

  /**
   * The number of structural features of the '<em>Select Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectExpressionImpl <em>Select Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectExpressionImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getSelectExpression()
   * @generated
   */
  int SELECT_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_EXPRESSION__EXPRESSION = 0;

  /**
   * The feature id for the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_EXPRESSION__ALIAS = 1;

  /**
   * The number of structural features of the '<em>Select Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.PathExpressionImpl <em>Path Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.PathExpressionImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getPathExpression()
   * @generated
   */
  int PATH_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Head</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_EXPRESSION__HEAD = 0;

  /**
   * The feature id for the '<em><b>Tail</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_EXPRESSION__TAIL = 1;

  /**
   * The number of structural features of the '<em>Path Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.PathElementImpl <em>Path Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.PathElementImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getPathElement()
   * @generated
   */
  int PATH_ELEMENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Path Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionCallImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 9;

  /**
   * The feature id for the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__FUNCTION = 0;

  /**
   * The feature id for the '<em><b>Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__ARGUMENTS = 1;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionArgumentImpl <em>Function Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionArgumentImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getFunctionArgument()
   * @generated
   */
  int FUNCTION_ARGUMENT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_ARGUMENT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Function Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_ARGUMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.LiteralImpl <em>Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.LiteralImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getLiteral()
   * @generated
   */
  int LITERAL = 11;

  /**
   * The number of structural features of the '<em>Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.IntegerLiteralImpl <em>Integer Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.IntegerLiteralImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getIntegerLiteral()
   * @generated
   */
  int INTEGER_LITERAL = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_LITERAL__VALUE = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Integer Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.StringLiteralImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VALUE = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.BooleanLiteralImpl
   * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getBooleanLiteral()
   * @generated
   */
  int BOOLEAN_LITERAL = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL__VALUE = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the containment reference '{@link nl.coenbijlsma.languages.d3ql.d3ql.Query#getFromStatement <em>From Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From Statement</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.Query#getFromStatement()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_FromStatement();

  /**
   * Returns the meta object for the containment reference '{@link nl.coenbijlsma.languages.d3ql.d3ql.Query#getSelectStatement <em>Select Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Select Statement</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.Query#getSelectStatement()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_SelectStatement();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.FromStatement <em>From Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>From Statement</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.FromStatement
   * @generated
   */
  EClass getFromStatement();

  /**
   * Returns the meta object for the containment reference list '{@link nl.coenbijlsma.languages.d3ql.d3ql.FromStatement#getAggregates <em>Aggregates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Aggregates</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.FromStatement#getAggregates()
   * @see #getFromStatement()
   * @generated
   */
  EReference getFromStatement_Aggregates();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.Named <em>Named</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Named</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.Named
   * @generated
   */
  EClass getNamed();

  /**
   * Returns the meta object for the attribute '{@link nl.coenbijlsma.languages.d3ql.d3ql.Named#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.Named#getName()
   * @see #getNamed()
   * @generated
   */
  EAttribute getNamed_Name();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.AggregateRoot <em>Aggregate Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aggregate Root</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.AggregateRoot
   * @generated
   */
  EClass getAggregateRoot();

  /**
   * Returns the meta object for the containment reference '{@link nl.coenbijlsma.languages.d3ql.d3ql.AggregateRoot#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alias</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.AggregateRoot#getAlias()
   * @see #getAggregateRoot()
   * @generated
   */
  EReference getAggregateRoot_Alias();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.Alias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alias</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.Alias
   * @generated
   */
  EClass getAlias();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.SelectStatement <em>Select Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Statement</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.SelectStatement
   * @generated
   */
  EClass getSelectStatement();

  /**
   * Returns the meta object for the containment reference list '{@link nl.coenbijlsma.languages.d3ql.d3ql.SelectStatement#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.SelectStatement#getExpressions()
   * @see #getSelectStatement()
   * @generated
   */
  EReference getSelectStatement_Expressions();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.SelectExpression <em>Select Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Expression</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.SelectExpression
   * @generated
   */
  EClass getSelectExpression();

  /**
   * Returns the meta object for the containment reference '{@link nl.coenbijlsma.languages.d3ql.d3ql.SelectExpression#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.SelectExpression#getExpression()
   * @see #getSelectExpression()
   * @generated
   */
  EReference getSelectExpression_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.coenbijlsma.languages.d3ql.d3ql.SelectExpression#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alias</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.SelectExpression#getAlias()
   * @see #getSelectExpression()
   * @generated
   */
  EReference getSelectExpression_Alias();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.PathExpression <em>Path Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Expression</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.PathExpression
   * @generated
   */
  EClass getPathExpression();

  /**
   * Returns the meta object for the reference '{@link nl.coenbijlsma.languages.d3ql.d3ql.PathExpression#getHead <em>Head</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Head</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.PathExpression#getHead()
   * @see #getPathExpression()
   * @generated
   */
  EReference getPathExpression_Head();

  /**
   * Returns the meta object for the containment reference list '{@link nl.coenbijlsma.languages.d3ql.d3ql.PathExpression#getTail <em>Tail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tail</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.PathExpression#getTail()
   * @see #getPathExpression()
   * @generated
   */
  EReference getPathExpression_Tail();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.PathElement <em>Path Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Element</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.PathElement
   * @generated
   */
  EClass getPathElement();

  /**
   * Returns the meta object for the attribute '{@link nl.coenbijlsma.languages.d3ql.d3ql.PathElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.PathElement#getName()
   * @see #getPathElement()
   * @generated
   */
  EAttribute getPathElement_Name();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for the attribute '{@link nl.coenbijlsma.languages.d3ql.d3ql.FunctionCall#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.FunctionCall#getFunction()
   * @see #getFunctionCall()
   * @generated
   */
  EAttribute getFunctionCall_Function();

  /**
   * Returns the meta object for the containment reference list '{@link nl.coenbijlsma.languages.d3ql.d3ql.FunctionCall#getArguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arguments</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.FunctionCall#getArguments()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Arguments();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.FunctionArgument <em>Function Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Argument</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.FunctionArgument
   * @generated
   */
  EClass getFunctionArgument();

  /**
   * Returns the meta object for the containment reference '{@link nl.coenbijlsma.languages.d3ql.d3ql.FunctionArgument#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.FunctionArgument#getValue()
   * @see #getFunctionArgument()
   * @generated
   */
  EReference getFunctionArgument_Value();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.Literal <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.Literal
   * @generated
   */
  EClass getLiteral();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.IntegerLiteral <em>Integer Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer Literal</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.IntegerLiteral
   * @generated
   */
  EClass getIntegerLiteral();

  /**
   * Returns the meta object for the attribute '{@link nl.coenbijlsma.languages.d3ql.d3ql.IntegerLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.IntegerLiteral#getValue()
   * @see #getIntegerLiteral()
   * @generated
   */
  EAttribute getIntegerLiteral_Value();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link nl.coenbijlsma.languages.d3ql.d3ql.StringLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.StringLiteral#getValue()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Value();

  /**
   * Returns the meta object for class '{@link nl.coenbijlsma.languages.d3ql.d3ql.BooleanLiteral <em>Boolean Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Literal</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.BooleanLiteral
   * @generated
   */
  EClass getBooleanLiteral();

  /**
   * Returns the meta object for the attribute '{@link nl.coenbijlsma.languages.d3ql.d3ql.BooleanLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.BooleanLiteral#getValue()
   * @see #getBooleanLiteral()
   * @generated
   */
  EAttribute getBooleanLiteral_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  D3qlFactory getD3qlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.QueryImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>From Statement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__FROM_STATEMENT = eINSTANCE.getQuery_FromStatement();

    /**
     * The meta object literal for the '<em><b>Select Statement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__SELECT_STATEMENT = eINSTANCE.getQuery_SelectStatement();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.FromStatementImpl <em>From Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.FromStatementImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getFromStatement()
     * @generated
     */
    EClass FROM_STATEMENT = eINSTANCE.getFromStatement();

    /**
     * The meta object literal for the '<em><b>Aggregates</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FROM_STATEMENT__AGGREGATES = eINSTANCE.getFromStatement_Aggregates();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.NamedImpl <em>Named</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.NamedImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getNamed()
     * @generated
     */
    EClass NAMED = eINSTANCE.getNamed();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMED__NAME = eINSTANCE.getNamed_Name();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.AggregateRootImpl <em>Aggregate Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.AggregateRootImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getAggregateRoot()
     * @generated
     */
    EClass AGGREGATE_ROOT = eINSTANCE.getAggregateRoot();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGGREGATE_ROOT__ALIAS = eINSTANCE.getAggregateRoot_Alias();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.AliasImpl <em>Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.AliasImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getAlias()
     * @generated
     */
    EClass ALIAS = eINSTANCE.getAlias();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectStatementImpl <em>Select Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectStatementImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getSelectStatement()
     * @generated
     */
    EClass SELECT_STATEMENT = eINSTANCE.getSelectStatement();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_STATEMENT__EXPRESSIONS = eINSTANCE.getSelectStatement_Expressions();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectExpressionImpl <em>Select Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.SelectExpressionImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getSelectExpression()
     * @generated
     */
    EClass SELECT_EXPRESSION = eINSTANCE.getSelectExpression();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_EXPRESSION__EXPRESSION = eINSTANCE.getSelectExpression_Expression();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_EXPRESSION__ALIAS = eINSTANCE.getSelectExpression_Alias();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.PathExpressionImpl <em>Path Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.PathExpressionImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getPathExpression()
     * @generated
     */
    EClass PATH_EXPRESSION = eINSTANCE.getPathExpression();

    /**
     * The meta object literal for the '<em><b>Head</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_EXPRESSION__HEAD = eINSTANCE.getPathExpression_Head();

    /**
     * The meta object literal for the '<em><b>Tail</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_EXPRESSION__TAIL = eINSTANCE.getPathExpression_Tail();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.PathElementImpl <em>Path Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.PathElementImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getPathElement()
     * @generated
     */
    EClass PATH_ELEMENT = eINSTANCE.getPathElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH_ELEMENT__NAME = eINSTANCE.getPathElement_Name();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionCallImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_CALL__FUNCTION = eINSTANCE.getFunctionCall_Function();

    /**
     * The meta object literal for the '<em><b>Arguments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__ARGUMENTS = eINSTANCE.getFunctionCall_Arguments();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionArgumentImpl <em>Function Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.FunctionArgumentImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getFunctionArgument()
     * @generated
     */
    EClass FUNCTION_ARGUMENT = eINSTANCE.getFunctionArgument();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_ARGUMENT__VALUE = eINSTANCE.getFunctionArgument_Value();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.LiteralImpl <em>Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.LiteralImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getLiteral()
     * @generated
     */
    EClass LITERAL = eINSTANCE.getLiteral();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.IntegerLiteralImpl <em>Integer Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.IntegerLiteralImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getIntegerLiteral()
     * @generated
     */
    EClass INTEGER_LITERAL = eINSTANCE.getIntegerLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER_LITERAL__VALUE = eINSTANCE.getIntegerLiteral_Value();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.StringLiteralImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VALUE = eINSTANCE.getStringLiteral_Value();

    /**
     * The meta object literal for the '{@link nl.coenbijlsma.languages.d3ql.d3ql.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.BooleanLiteralImpl
     * @see nl.coenbijlsma.languages.d3ql.d3ql.impl.D3qlPackageImpl#getBooleanLiteral()
     * @generated
     */
    EClass BOOLEAN_LITERAL = eINSTANCE.getBooleanLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_LITERAL__VALUE = eINSTANCE.getBooleanLiteral_Value();

  }

} //D3qlPackage
