/**
 * generated by Xtext 2.9.2
 */
package nl.coenbijlsma.languages.d3ql.d3ql;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.coenbijlsma.languages.d3ql.d3ql.SelectStatement#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see nl.coenbijlsma.languages.d3ql.d3ql.D3qlPackage#getSelectStatement()
 * @model
 * @generated
 */
public interface SelectStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link nl.coenbijlsma.languages.d3ql.d3ql.SelectExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see nl.coenbijlsma.languages.d3ql.d3ql.D3qlPackage#getSelectStatement_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<SelectExpression> getExpressions();

} // SelectStatement
