/*
 * generated by Xtext 2.9.2
 */
package nl.coenbijlsma.languages.d3ql.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class D3qlProposalProvider extends AbstractD3qlProposalProvider {
}
