/*
 * generated by Xtext 2.9.2
 */
package nl.coenbijlsma.languages.d3ql.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class D3qlGrammarAccess extends AbstractGrammarElementFinder {
	
	public class QueryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.Query");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFromStatementAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFromStatementFromStatementParserRuleCall_0_0 = (RuleCall)cFromStatementAssignment_0.eContents().get(0);
		private final Assignment cSelectStatementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSelectStatementSelectStatementParserRuleCall_1_0 = (RuleCall)cSelectStatementAssignment_1.eContents().get(0);
		
		//Query:
		//	fromStatement=FromStatement selectStatement=SelectStatement;
		@Override public ParserRule getRule() { return rule; }
		
		//fromStatement=FromStatement selectStatement=SelectStatement
		public Group getGroup() { return cGroup; }
		
		//fromStatement=FromStatement
		public Assignment getFromStatementAssignment_0() { return cFromStatementAssignment_0; }
		
		//FromStatement
		public RuleCall getFromStatementFromStatementParserRuleCall_0_0() { return cFromStatementFromStatementParserRuleCall_0_0; }
		
		//selectStatement=SelectStatement
		public Assignment getSelectStatementAssignment_1() { return cSelectStatementAssignment_1; }
		
		//SelectStatement
		public RuleCall getSelectStatementSelectStatementParserRuleCall_1_0() { return cSelectStatementSelectStatementParserRuleCall_1_0; }
	}
	public class FromStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.FromStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFromKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAggregatesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAggregatesAggregateRootParserRuleCall_1_0 = (RuleCall)cAggregatesAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAggregatesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAggregatesAggregateRootParserRuleCall_2_1_0 = (RuleCall)cAggregatesAssignment_2_1.eContents().get(0);
		
		//FromStatement:
		//	'from' aggregates+=AggregateRoot (',' aggregates+=AggregateRoot)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'from' aggregates+=AggregateRoot (',' aggregates+=AggregateRoot)*
		public Group getGroup() { return cGroup; }
		
		//'from'
		public Keyword getFromKeyword_0() { return cFromKeyword_0; }
		
		//aggregates+=AggregateRoot
		public Assignment getAggregatesAssignment_1() { return cAggregatesAssignment_1; }
		
		//AggregateRoot
		public RuleCall getAggregatesAggregateRootParserRuleCall_1_0() { return cAggregatesAggregateRootParserRuleCall_1_0; }
		
		//(',' aggregates+=AggregateRoot)*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//aggregates+=AggregateRoot
		public Assignment getAggregatesAssignment_2_1() { return cAggregatesAssignment_2_1; }
		
		//AggregateRoot
		public RuleCall getAggregatesAggregateRootParserRuleCall_2_1_0() { return cAggregatesAggregateRootParserRuleCall_2_1_0; }
	}
	public class NamedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.Named");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAggregateRootParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAliasParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Named:
		//	AggregateRoot | Alias;
		@Override public ParserRule getRule() { return rule; }
		
		//AggregateRoot | Alias
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AggregateRoot
		public RuleCall getAggregateRootParserRuleCall_0() { return cAggregateRootParserRuleCall_0; }
		
		//Alias
		public RuleCall getAliasParserRuleCall_1() { return cAliasParserRuleCall_1; }
	}
	public class AggregateRootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.AggregateRoot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAsKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAliasAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAliasAliasParserRuleCall_1_1_0 = (RuleCall)cAliasAssignment_1_1.eContents().get(0);
		
		//AggregateRoot:
		//	name=ID ('as' alias=Alias)?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('as' alias=Alias)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('as' alias=Alias)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'as'
		public Keyword getAsKeyword_1_0() { return cAsKeyword_1_0; }
		
		//alias=Alias
		public Assignment getAliasAssignment_1_1() { return cAliasAssignment_1_1; }
		
		//Alias
		public RuleCall getAliasAliasParserRuleCall_1_1_0() { return cAliasAliasParserRuleCall_1_1_0; }
	}
	public class AliasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.Alias");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Alias:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class SelectStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.SelectStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExpressionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpressionsSelectExpressionParserRuleCall_1_0 = (RuleCall)cExpressionsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cExpressionsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cExpressionsSelectExpressionParserRuleCall_2_1_0 = (RuleCall)cExpressionsAssignment_2_1.eContents().get(0);
		
		//SelectStatement:
		//	'select' expressions+=SelectExpression (',' expressions+=SelectExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'select' expressions+=SelectExpression (',' expressions+=SelectExpression)*
		public Group getGroup() { return cGroup; }
		
		//'select'
		public Keyword getSelectKeyword_0() { return cSelectKeyword_0; }
		
		//expressions+=SelectExpression
		public Assignment getExpressionsAssignment_1() { return cExpressionsAssignment_1; }
		
		//SelectExpression
		public RuleCall getExpressionsSelectExpressionParserRuleCall_1_0() { return cExpressionsSelectExpressionParserRuleCall_1_0; }
		
		//(',' expressions+=SelectExpression)*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//expressions+=SelectExpression
		public Assignment getExpressionsAssignment_2_1() { return cExpressionsAssignment_2_1; }
		
		//SelectExpression
		public RuleCall getExpressionsSelectExpressionParserRuleCall_2_1_0() { return cExpressionsSelectExpressionParserRuleCall_2_1_0; }
	}
	public class SelectExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.SelectExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cExpressionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cExpressionAlternatives_0_0 = (Alternatives)cExpressionAssignment_0.eContents().get(0);
		private final RuleCall cExpressionPathExpressionParserRuleCall_0_0_0 = (RuleCall)cExpressionAlternatives_0_0.eContents().get(0);
		private final RuleCall cExpressionFunctionCallParserRuleCall_0_0_1 = (RuleCall)cExpressionAlternatives_0_0.eContents().get(1);
		private final RuleCall cExpressionLiteralParserRuleCall_0_0_2 = (RuleCall)cExpressionAlternatives_0_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAsKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAliasAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAliasAliasParserRuleCall_1_1_0 = (RuleCall)cAliasAssignment_1_1.eContents().get(0);
		
		//SelectExpression:
		//	expression=(PathExpression | FunctionCall | Literal) ('as' alias=Alias)?;
		@Override public ParserRule getRule() { return rule; }
		
		//expression=(PathExpression | FunctionCall | Literal) ('as' alias=Alias)?
		public Group getGroup() { return cGroup; }
		
		//expression=(PathExpression | FunctionCall | Literal)
		public Assignment getExpressionAssignment_0() { return cExpressionAssignment_0; }
		
		//(PathExpression | FunctionCall | Literal)
		public Alternatives getExpressionAlternatives_0_0() { return cExpressionAlternatives_0_0; }
		
		//PathExpression
		public RuleCall getExpressionPathExpressionParserRuleCall_0_0_0() { return cExpressionPathExpressionParserRuleCall_0_0_0; }
		
		//FunctionCall
		public RuleCall getExpressionFunctionCallParserRuleCall_0_0_1() { return cExpressionFunctionCallParserRuleCall_0_0_1; }
		
		//Literal
		public RuleCall getExpressionLiteralParserRuleCall_0_0_2() { return cExpressionLiteralParserRuleCall_0_0_2; }
		
		//('as' alias=Alias)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'as'
		public Keyword getAsKeyword_1_0() { return cAsKeyword_1_0; }
		
		//alias=Alias
		public Assignment getAliasAssignment_1_1() { return cAliasAssignment_1_1; }
		
		//Alias
		public RuleCall getAliasAliasParserRuleCall_1_1_0() { return cAliasAliasParserRuleCall_1_1_0; }
	}
	public class PathExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.PathExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHeadAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cHeadNamedCrossReference_0_0 = (CrossReference)cHeadAssignment_0.eContents().get(0);
		private final RuleCall cHeadNamedIDTerminalRuleCall_0_0_1 = (RuleCall)cHeadNamedCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cTailAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cTailPathElementParserRuleCall_1_1_0_0 = (RuleCall)cTailAssignment_1_1_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cTailAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cTailPathElementParserRuleCall_1_2_0 = (RuleCall)cTailAssignment_1_2.eContents().get(0);
		
		//PathExpression:
		//	head=[Named] ('.' (tail+=PathElement '.')* tail+=PathElement)?;
		@Override public ParserRule getRule() { return rule; }
		
		//head=[Named] ('.' (tail+=PathElement '.')* tail+=PathElement)?
		public Group getGroup() { return cGroup; }
		
		//head=[Named]
		public Assignment getHeadAssignment_0() { return cHeadAssignment_0; }
		
		//[Named]
		public CrossReference getHeadNamedCrossReference_0_0() { return cHeadNamedCrossReference_0_0; }
		
		//ID
		public RuleCall getHeadNamedIDTerminalRuleCall_0_0_1() { return cHeadNamedIDTerminalRuleCall_0_0_1; }
		
		//('.' (tail+=PathElement '.')* tail+=PathElement)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//(tail+=PathElement '.')*
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//tail+=PathElement
		public Assignment getTailAssignment_1_1_0() { return cTailAssignment_1_1_0; }
		
		//PathElement
		public RuleCall getTailPathElementParserRuleCall_1_1_0_0() { return cTailPathElementParserRuleCall_1_1_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1_1_1() { return cFullStopKeyword_1_1_1; }
		
		//tail+=PathElement
		public Assignment getTailAssignment_1_2() { return cTailAssignment_1_2; }
		
		//PathElement
		public RuleCall getTailPathElementParserRuleCall_1_2_0() { return cTailPathElementParserRuleCall_1_2_0; }
	}
	public class PathElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.PathElement");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//PathElement:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class FunctionCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.FunctionCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFunctionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFunctionIDTerminalRuleCall_0_0 = (RuleCall)cFunctionAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cArgumentsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cArgumentsFunctionArgumentParserRuleCall_2_0 = (RuleCall)cArgumentsAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cArgumentsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cArgumentsFunctionArgumentParserRuleCall_3_1_0 = (RuleCall)cArgumentsAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//FunctionCall:
		//	function=ID '(' arguments+=FunctionArgument (',' arguments+=FunctionArgument)* ')';
		@Override public ParserRule getRule() { return rule; }
		
		//function=ID '(' arguments+=FunctionArgument (',' arguments+=FunctionArgument)* ')'
		public Group getGroup() { return cGroup; }
		
		//function=ID
		public Assignment getFunctionAssignment_0() { return cFunctionAssignment_0; }
		
		//ID
		public RuleCall getFunctionIDTerminalRuleCall_0_0() { return cFunctionIDTerminalRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//arguments+=FunctionArgument
		public Assignment getArgumentsAssignment_2() { return cArgumentsAssignment_2; }
		
		//FunctionArgument
		public RuleCall getArgumentsFunctionArgumentParserRuleCall_2_0() { return cArgumentsFunctionArgumentParserRuleCall_2_0; }
		
		//(',' arguments+=FunctionArgument)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//arguments+=FunctionArgument
		public Assignment getArgumentsAssignment_3_1() { return cArgumentsAssignment_3_1; }
		
		//FunctionArgument
		public RuleCall getArgumentsFunctionArgumentParserRuleCall_3_1_0() { return cArgumentsFunctionArgumentParserRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class FunctionArgumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.FunctionArgument");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cValueAlternatives_0 = (Alternatives)cValueAssignment.eContents().get(0);
		private final RuleCall cValuePathExpressionParserRuleCall_0_0 = (RuleCall)cValueAlternatives_0.eContents().get(0);
		private final RuleCall cValueLiteralParserRuleCall_0_1 = (RuleCall)cValueAlternatives_0.eContents().get(1);
		
		//FunctionArgument:
		//	value=(PathExpression | Literal);
		@Override public ParserRule getRule() { return rule; }
		
		//value=(PathExpression | Literal)
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//(PathExpression | Literal)
		public Alternatives getValueAlternatives_0() { return cValueAlternatives_0; }
		
		//PathExpression
		public RuleCall getValuePathExpressionParserRuleCall_0_0() { return cValuePathExpressionParserRuleCall_0_0; }
		
		//Literal
		public RuleCall getValueLiteralParserRuleCall_0_1() { return cValueLiteralParserRuleCall_0_1; }
	}
	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.Literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntegerLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBooleanLiteralParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Literal:
		//	IntegerLiteral | StringLiteral | BooleanLiteral;
		@Override public ParserRule getRule() { return rule; }
		
		//IntegerLiteral | StringLiteral | BooleanLiteral
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntegerLiteral
		public RuleCall getIntegerLiteralParserRuleCall_0() { return cIntegerLiteralParserRuleCall_0; }
		
		//StringLiteral
		public RuleCall getStringLiteralParserRuleCall_1() { return cStringLiteralParserRuleCall_1; }
		
		//BooleanLiteral
		public RuleCall getBooleanLiteralParserRuleCall_2() { return cBooleanLiteralParserRuleCall_2; }
	}
	public class IntegerLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.IntegerLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntegerLiteral:
		//	value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class StringLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.StringLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringLiteral:
		//	value=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}
	public class BooleanLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.coenbijlsma.languages.d3ql.D3ql.BooleanLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cValueAlternatives_0 = (Alternatives)cValueAssignment.eContents().get(0);
		private final Keyword cValueTrueKeyword_0_0 = (Keyword)cValueAlternatives_0.eContents().get(0);
		private final Keyword cValueFalseKeyword_0_1 = (Keyword)cValueAlternatives_0.eContents().get(1);
		
		//BooleanLiteral:
		//	value=('true' | 'false');
		@Override public ParserRule getRule() { return rule; }
		
		//value=('true' | 'false')
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//('true' | 'false')
		public Alternatives getValueAlternatives_0() { return cValueAlternatives_0; }
		
		//'true'
		public Keyword getValueTrueKeyword_0_0() { return cValueTrueKeyword_0_0; }
		
		//'false'
		public Keyword getValueFalseKeyword_0_1() { return cValueFalseKeyword_0_1; }
	}
	
	
	private final QueryElements pQuery;
	private final FromStatementElements pFromStatement;
	private final NamedElements pNamed;
	private final AggregateRootElements pAggregateRoot;
	private final AliasElements pAlias;
	private final SelectStatementElements pSelectStatement;
	private final SelectExpressionElements pSelectExpression;
	private final PathExpressionElements pPathExpression;
	private final PathElementElements pPathElement;
	private final FunctionCallElements pFunctionCall;
	private final FunctionArgumentElements pFunctionArgument;
	private final LiteralElements pLiteral;
	private final IntegerLiteralElements pIntegerLiteral;
	private final StringLiteralElements pStringLiteral;
	private final BooleanLiteralElements pBooleanLiteral;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public D3qlGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pQuery = new QueryElements();
		this.pFromStatement = new FromStatementElements();
		this.pNamed = new NamedElements();
		this.pAggregateRoot = new AggregateRootElements();
		this.pAlias = new AliasElements();
		this.pSelectStatement = new SelectStatementElements();
		this.pSelectExpression = new SelectExpressionElements();
		this.pPathExpression = new PathExpressionElements();
		this.pPathElement = new PathElementElements();
		this.pFunctionCall = new FunctionCallElements();
		this.pFunctionArgument = new FunctionArgumentElements();
		this.pLiteral = new LiteralElements();
		this.pIntegerLiteral = new IntegerLiteralElements();
		this.pStringLiteral = new StringLiteralElements();
		this.pBooleanLiteral = new BooleanLiteralElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("nl.coenbijlsma.languages.d3ql.D3ql".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Query:
	//	fromStatement=FromStatement selectStatement=SelectStatement;
	public QueryElements getQueryAccess() {
		return pQuery;
	}
	
	public ParserRule getQueryRule() {
		return getQueryAccess().getRule();
	}
	
	//FromStatement:
	//	'from' aggregates+=AggregateRoot (',' aggregates+=AggregateRoot)*;
	public FromStatementElements getFromStatementAccess() {
		return pFromStatement;
	}
	
	public ParserRule getFromStatementRule() {
		return getFromStatementAccess().getRule();
	}
	
	//Named:
	//	AggregateRoot | Alias;
	public NamedElements getNamedAccess() {
		return pNamed;
	}
	
	public ParserRule getNamedRule() {
		return getNamedAccess().getRule();
	}
	
	//AggregateRoot:
	//	name=ID ('as' alias=Alias)?;
	public AggregateRootElements getAggregateRootAccess() {
		return pAggregateRoot;
	}
	
	public ParserRule getAggregateRootRule() {
		return getAggregateRootAccess().getRule();
	}
	
	//Alias:
	//	name=ID;
	public AliasElements getAliasAccess() {
		return pAlias;
	}
	
	public ParserRule getAliasRule() {
		return getAliasAccess().getRule();
	}
	
	//SelectStatement:
	//	'select' expressions+=SelectExpression (',' expressions+=SelectExpression)*;
	public SelectStatementElements getSelectStatementAccess() {
		return pSelectStatement;
	}
	
	public ParserRule getSelectStatementRule() {
		return getSelectStatementAccess().getRule();
	}
	
	//SelectExpression:
	//	expression=(PathExpression | FunctionCall | Literal) ('as' alias=Alias)?;
	public SelectExpressionElements getSelectExpressionAccess() {
		return pSelectExpression;
	}
	
	public ParserRule getSelectExpressionRule() {
		return getSelectExpressionAccess().getRule();
	}
	
	//PathExpression:
	//	head=[Named] ('.' (tail+=PathElement '.')* tail+=PathElement)?;
	public PathExpressionElements getPathExpressionAccess() {
		return pPathExpression;
	}
	
	public ParserRule getPathExpressionRule() {
		return getPathExpressionAccess().getRule();
	}
	
	//PathElement:
	//	name=ID;
	public PathElementElements getPathElementAccess() {
		return pPathElement;
	}
	
	public ParserRule getPathElementRule() {
		return getPathElementAccess().getRule();
	}
	
	//FunctionCall:
	//	function=ID '(' arguments+=FunctionArgument (',' arguments+=FunctionArgument)* ')';
	public FunctionCallElements getFunctionCallAccess() {
		return pFunctionCall;
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}
	
	//FunctionArgument:
	//	value=(PathExpression | Literal);
	public FunctionArgumentElements getFunctionArgumentAccess() {
		return pFunctionArgument;
	}
	
	public ParserRule getFunctionArgumentRule() {
		return getFunctionArgumentAccess().getRule();
	}
	
	//Literal:
	//	IntegerLiteral | StringLiteral | BooleanLiteral;
	public LiteralElements getLiteralAccess() {
		return pLiteral;
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}
	
	//IntegerLiteral:
	//	value=INT;
	public IntegerLiteralElements getIntegerLiteralAccess() {
		return pIntegerLiteral;
	}
	
	public ParserRule getIntegerLiteralRule() {
		return getIntegerLiteralAccess().getRule();
	}
	
	//StringLiteral:
	//	value=STRING;
	public StringLiteralElements getStringLiteralAccess() {
		return pStringLiteral;
	}
	
	public ParserRule getStringLiteralRule() {
		return getStringLiteralAccess().getRule();
	}
	
	//BooleanLiteral:
	//	value=('true' | 'false');
	public BooleanLiteralElements getBooleanLiteralAccess() {
		return pBooleanLiteral;
	}
	
	public ParserRule getBooleanLiteralRule() {
		return getBooleanLiteralAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
